lambda function to re-index items to ES
zotero/full-text-indexer pull request #2
Opened 2023-06-16 21:00 UTC by abaevbog

Async lambda function invoked directly from dataserver that re-adds items deleted from ES to the dlq to be indexed again.

2023-06-20 09:22 UTC, dstillman requested changes

2023-06-20 09:22 UTC, dstillman commented on template.yaml.j2
> +      Timeout: 300
This might as well be set to the maximum (900 seconds).

2023-06-20 09:22 UTC, dstillman commented on template.yaml.j2
> +  FullTextReIndexerFunction:
Lowercase `I` here and below

2023-06-20 09:22 UTC, dstillman commented on index.mjs
> +export const reindexDeletedLibrary = async (event) => {
Can remove "Deleted". Theoretically it should only be necessary for deleted libraries, but as far as the function is concerned it's just reindexing a library with what's in S3.

2023-06-20 09:22 UTC, dstillman commented on index.mjs
> +	} while (continuationToken);
Probably no difference, but I think `.IsTruncated` is the [more canonical](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ListingKeysUsingAPIs.html) way to do this.

2023-06-20 09:22 UTC, dstillman commented on index.mjs
> +		sqsEventsArray = sqsEventsArray.concat(sqsEvents);
There could be tens or hundreds of thousands of files in a library, so we don't want to combine these all in one array. They should just get sent out in batches as they're available, and then it can get more from S3 as necessary.

2023-06-20 09:22 UTC, dstillman commented on index.mjs
> +	const libraryId = event.libraryID;
House style: `libraryID`

2023-06-20 09:22 UTC, dstillman commented on index.mjs
> +			return { Id: entry.Key.replace("/", "-"), MessageBody: JSON.stringify(message) };
House style: Separate over multiple lines (other places too)

2024-02-12 21:45 UTC, dstillman reviewed
I just realized I had pending comments here. Not sure if they made sense, but let's load this and https://github.com/zotero/dataserver/pull/151 back into RAM and get them merged.

2024-02-12 21:45 UTC, dstillman commented on index.mjs
> +	let sqs = new SQSClient();
Move down to above the code where it's used

2024-02-12 21:45 UTC, dstillman commented on index.mjs
> +	var isTruncated = true;
Should move down to above the block where this is used, but we can just use a do/while and avoid a separate variable.

2024-02-12 21:45 UTC, dstillman commented on index.mjs
> +	let sqsSendEventPromisses = [];
`Promisses` → `Promises`, and move down to above the code where it's used

2024-02-12 21:45 UTC, dstillman commented on index.mjs
> +		}
Why two separate loops? Can just get 10 events at a time and send them off.

2024-02-12 21:45 UTC, dstillman commented on template.yaml.j2
> +      Handler: index.reindexDeletedLibrary
This need to be updated.

2024-02-12 21:45 UTC, dstillman commented on index.mjs
> +	const reindexRequestDate = event.date;
What is `event.date`? I'm not seeing that in https://github.com/zotero/dataserver/pull/151.

If this is a timestamp, it'd be clearer to call it `reindexRequestTime`. But if the goal is just to uniquely identify a run, shouldn't it just be a UUID or random string?

2024-02-12 21:45 UTC, dstillman commented on index.mjs
> +	reindexStatus.status = "inProgress";
If complete and request identifier isn't the same, we should clear `.items`, right? Otherwise deleted items would never be removed.

2024-02-12 21:45 UTC, dstillman commented on index.mjs
> +		}
Is there any reason to store the request identifier for every item? Don't we only care 1) whether a given requested reindex failed to finish and 2) if it did, which items were already processed? So can't we just store the request identifier and the items processed so far?

And on completion, should we not delete the reindex file? What's the value of `Complete`? I'm not totally clear on the circumstances under which an SQS message [can be delivered multiple times](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues.html#standard-queues-at-least-once-delivery), but it seems unlikely that the same message would be delivered once the Lambda competes successfully.

2024-02-14 20:58 UTC, abaevbog commented
I would like to go over the general logic here and outline what revisions I made, to make sure it's all on the right track. 

Our goal is to have this be a long running operation that re-indexes all items from the library to ES, that is initiated asynchronously from dataserver, and we also need a way to also tell when it started and when it was done.

Initially, the dataserver was asynchronously triggering the lambda function that ran through all S3 items and added them to DLQ for reindexing. I thought there were a few issues with this approach: 1. async lambda trigger can loose the event in case of breakage (unlikely but still could happen if all retries fail, like during an outage - especially if it's a very large library with many s3 files) 2. with DLQ being a non FIFO queue, it is hard to tell when exactly reindexing is finished. Because if the last item is indexed, it does not mean that all other items were, so we would have to somehow check how many records were indexed vs how many should be and it seemed quite messy.

I tried a somewhat alternative approach that (I think) makes it easier to tell when reindexing is done. The new lambda does not interact with DLQ or other lambdas. It is triggered when dataserver adds an event to a new `FullTextReIndexerQueue`. Using that queue ensures that the event is never lost. Then, this lambda runs through items in S3 in batches, and for every batch, it creates a fake event and calls `processEvent` to add the item to ES. After a batch has been processed, we record the keys that were indexed in a special `_reindex_status` file. If this lambda times out or breaks, the next lambda that picks up that SQS event will use that file to skip already indexed items. That way, once the lambda actually finishes and updates `_reindex_status` with `status=complete`, this tells us if reindexing is done (likely exposed through another dataserver endpoint, like `fulltext/reindex/status` that will just check for existence and status in `_reindex_status` file). The only question there is if/when should that file be removed? I suppose it somewhat depends on how web library would use it

I'm still doing some testing but so far reindexing 1000 items from S3 with a lowered lambda timeout of 20 seconds runs as expected with indexing, recording what was done, and picking up after it on the next run.

2024-02-15 04:05 UTC, abaevbog commented
The flip side of this essentially sequential processing is that it might take much longer for a large library to be indexed, so I'm not sure if knowing the status when the entire batch is finished is worth the tradeoff. 

Question: would checking if `Zotero_FullText::countInLibrary($this->objectLibraryID)` is equal to `Zotero_Libraries::countAttachments($this->objectLibraryID)` be a reasonable alternative way to establish that the library has been fully re-indexed? If so, this last change wouldn't be needed and GET to `fulltext/reindex` could just check that

2024-02-16 18:20 UTC, abaevbog commented
I revised this to simplify the logic quite a bit and to work in tandem with [the dataserver PR](https://github.com/zotero/dataserver/pull/151). I did some testing with this lambda deployed with lower timeout values, and it worked as expected with my local instances of dataserver and ES

2026-06-09 14:44 UTC, merged